name: Update docs
on:
  workflow_dispatch:
  push:
    paths:
      - filters/**
      - yt-neuter.txt

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p docs/filters && node docs/gendocs.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Automated docs update
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>